Ik
uwrobotics/MarsRover2019 pull request #35
Opened 2018-11-17 08:36 UTC by roberttoyonaga

added forward kinematics function to Roboarm class to allow us to visualize the IK during testing

2018-11-20 02:26 UTC, OmarAlashqar requested changes
we should talk, now that we have some code down

2018-11-20 02:26 UTC, OmarAlashqar commented on Workspace/src/ik/include/ik/Roboarm.h
> +    float velocityLink2;
I'm starting to feel like we should just define the velocities as a member array and just return it in the `calc_velocities` method. This works with the `calc_pose` points as well, where we could return an array of (x, y) points.

2018-11-20 02:26 UTC, OmarAlashqar commented on Workspace/src/ik/src/Roboarm.cpp
> +        angleLink1 = nextAngle1;
I don't think we'll ever want to affect the `angleLink` values when we're just calculating a pose.

2018-11-22 05:12 UTC, roberttoyonaga commented on Workspace/src/ik/src/Roboarm.cpp
> +        angleLink1 = nextAngle1;
The angleLink values are only updated so that we can have a sort of closed loop including the IK and FK functions for visualizing.

2018-11-22 05:39 UTC, merged